version: '3'

services:
  rpi-alpine-glibc:
    image: bradsjm/rpi-alpine-glibc
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-alpine-glibc

  rpi-zulu-openjdk:
    image: bradsjm/rpi-zulu-openjdk
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-zulu-openjdk
    depends_on:
      - rpi-alpine-glibc

  rpi-gpsd:
    image: bradsjm/rpi-gpsd
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-gpsd

  rpi-chrony:
    image: bradsjm/rpi-chrony
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-chrony

  rpi-multimon-ng:
    image: bradsjm/rpi-multimon-ng
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-multimon-ng
    depends_on:
      - rpi-rtl-sdr

  rpi-direwolf:
    image: bradsjm/rpi-direwolf
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-direwolf
    depends_on:
      - rpi-rtl-sdr

  rpi-socat:
    image: bradsjm/rpi-socat
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-socat

  rpi-telegraf:
    image: bradsjm/rpi-telegraf
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-telegraf

  rpi-samba:
    image: bradsjm/rpi-samba
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-samba

  rpi-frontail:
    image: bradsjm/rpi-frontail
    build: https://github.com/bradsjm/Dockerfiles.git#:rpi-frontail

  homeseer3:
    image: bradsjm/homeseer3
    build: https://github.com/bradsjm/Dockerfiles.git#:homeseer3

  weewx:
    image: bradsjm/weewx
    build: https://github.com/bradsjm/Dockerfiles.git#:weewx
